### ISSUE TITLE
相关问题咨询

### ISSUE THREAD

**Issue by ylytddd** [fluttify-project/technical-support-plan#11]
## 技术支持类型 (咨询/bug修复/新功能/业务功能参考实现/新插件开发)
咨询
## 请求人联系方式 建议qq
465987368

**Comment by yohom** [comment]
**咨询问题1**：
修改了ios端[地图插件](https://github.com/fluttify-project/amap_map_fluttify)原生代码之后，无法添加marker。

**Comment by ylytddd** [comment]
#### 咨询问题2：
安卓release包闪退

**Comment by dsmjoy** [comment]
已解决

**Comment by dsmjoy** [comment]
咨询问题1已解决

**Comment by ylytddd** [comment]
> **咨询问题1**：
> 修改了ios端[地图插件](https://github.com/fluttify-project/amap_map_fluttify)原生代码之后，无法添加marker。

已解决

**Comment by ylytddd** [comment]
> #### 咨询问题2：
> 安卓release包闪退

已解决
