### ISSUE TITLE
marker居中后再向下偏移一定距离，ListView+stack里放地图滚动，listView会卡住无法回弹

### ISSUE THREAD

**Issue by WeiQiZhang** [fluttify-project/technical-support-plan#14]
## 技术支持类型 (咨询/bug修复/新功能/业务功能实现/新插件开发)
业务功能实现
## 请求人联系方式 建议qq
375468881
## 需要技术支持的仓库
amap_map_fluttify

**Comment by WeiQiZhang** [comment]
问题1：地图上部覆盖了一个Container（高度会自适应变化），marker缩放到地图中间并且向下偏移到Container下方居中

问题2：ListView里放，stack包装地图和Container，拖动ListView会卡住

**Comment by WeiQiZhang** [comment]
大佬我写了demo，如有需要可以qq提供demo

**Comment by yohom** [comment]
已解决
