### ISSUE TITLE
运行地图时候app闪退

### ISSUE THREAD

**Issue by GAONING-abc** [fluttify-project/technical-support-plan#3]
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   Runner                              0x0000000109dfef44 __57-[AmapLocationFluttifyPlugin(SubHandler0) getSubHandler0]_block_invoke_87 + 260
	6   Runner                              0x0000000109de2c07 -[AmapLocationFluttifyPlugin handleMethodCall:result:] + 359
	7   Flutter                             0x000000010a91bdb5 __45-[FlutterMethodChannel setM<…>
Lost connection to device.

**Comment by yohom** [comment]
老铁我先确认一下，你是有看过技术支持方案说明的吧？

**Comment by yohom** [comment]
由于当前issue不是有效的技术支持请求，先关闭了。
