### ISSUE TITLE
个推官方出的flutter版推送插件 “getuiflut: 0.1.7”

### ISSUE THREAD

**Issue by 5454267364** [fluttify-project/technical-support-plan#4]
## 技术支持类型 (咨询/bug修复/新功能/业务功能参考实现/新插件开发)
纯咨询
## 请求人联系方式 建议qq
QQ：1533264523
## 需要技术支持的仓库
getuiflut: 0.1.7

我想在接收到通知的时候根据参数跳转到页面，请问要怎么跳转，现在我是把监听写在main.dart里，我想只写一个监听就能在每一次接收到通知后跳转到我想要的页面

**Comment by yohom** [comment]
开始咨询

**Comment by 5454267364** [comment]
已解决

**Comment by 5454267364** [comment]
我是在main.dart里写的全局监听，可以这样跳转
![image](https://user-images.githubusercontent.com/48704489/76587185-0aa17880-651e-11ea-9777-0ac0332abf10.png)
![image](https://user-images.githubusercontent.com/48704489/76587198-12611d00-651e-11ea-8c89-35cd1180995e.png)
